CREATE DATABASE AGGR;

USE AGGR;

CREATE TABLE INFO(C1 INT, C2 INT, C3 FLOAT, C4 VARCHAR(10));
INSERT INTO INFO VALUES (1, 8, -3.0, 'A');
INSERT INTO INFO VALUES (2, 7, 3.0, 'B');
INSERT INTO INFO VALUES (3, 6, 1.1, 'C');
INSERT INTO INFO VALUES (4, 5, 1.1, 'A');
INSERT INTO INFO VALUES (-1, 4, 3.3, 'B');
INSERT INTO INFO VALUES (2, 3, 4.4, 'C');
INSERT INTO INFO VALUES (3, 2, 5.5, 'A');
INSERT INTO INFO VALUES (99, 6, 6.6, 'B');
INSERT INTO INFO VALUES (8, 6, 8.8, 'C');
INSERT INTO INFO VALUES (4, 5, 8.8, 'A');
INSERT INTO INFO VALUES (-1, 4, 9.9, 'B');
INSERT INTO INFO VALUES (233, -9, 10.1, 'C');
INSERT INTO INFO VALUES (73, 4, 9.9, 'B');
INSERT INTO INFO VALUES (2, 3, 10.1, 'C');
INSERT INTO INFO VALUES (-99, 4, 3.8, 'B');
INSERT INTO INFO VALUES (-7, 3, 36.3, 'C');
INSERT INTO INFO VALUES (2, 5, 3.8, 'C');

CREATE TABLE INFO2(C1 INT, C2 VARCHAR(10));
INSERT INTO INFO2 VALUES (333, 'A');
INSERT INTO INFO2 VALUES (666, 'A');
INSERT INTO INFO2 VALUES (999, 'B');
INSERT INTO INFO2 VALUES (777, 'C');
INSERT INTO INFO2 VALUES (111, 'C');
INSERT INTO INFO2 VALUES (222, 'C');

-- WITH GROUP BY;
SELECT INFO.C2, MIN(INFO.C1), MAX(INFO.C1), AVG(INFO.C1), SUM(INFO.C1), COUNT(INFO.C1), COUNT(*) FROM INFO GROUP BY INFO.C2; -- GROUP BY INT;
SELECT INFO.C3, MIN(INFO.C1), MAX(INFO.C1), AVG(INFO.C1), SUM(INFO.C1), COUNT(INFO.C1), COUNT(*) FROM INFO GROUP BY INFO.C3; -- GROUP BY FLOAT;
SELECT INFO.C4, MIN(INFO.C1), MAX(INFO.C1), AVG(INFO.C1), SUM(INFO.C1), COUNT(INFO.C1), COUNT(*) FROM INFO GROUP BY INFO.C4; -- GROUP BY STRING;
SELECT INFO.C4, MIN(INFO.C3), MAX(INFO.C3), AVG(INFO.C3), SUM(INFO.C3), COUNT(INFO.C3), COUNT(*) FROM INFO GROUP BY INFO.C4; -- AGGREGATE ON FLOAT;
SELECT COUNT(*) FROM INFO GROUP BY C1;

-- WITHOUT GROUP BY;
SELECT MIN(INFO.C1), MAX(INFO.C1), AVG(INFO.C1), SUM(INFO.C1), COUNT(INFO.C1), COUNT(*) FROM INFO;

-- WITH JOIN OPERATION;
SELECT INFO.C4, MIN(INFO.C1), MAX(INFO.C1), AVG(INFO.C1), SUM(INFO.C1), SUM(INFO2.C1), COUNT(*) FROM INFO, INFO2 WHERE INFO.C4 = INFO2.C2 GROUP BY INFO.C4;
