CREATE DATABASE TEST_COMPOSITE_CONSTRAINT;

USE TEST_COMPOSITE_CONSTRAINT;

-- CREATE COMPOSITE PRIMARY KEY ON CREATE TABLE;
CREATE TABLE R (
    X INT,
    Y INT,
    Z INT,
    W INT,
    V VARCHAR(100),

    PRIMARY KEY test_pk (Z, Y, X)
);

-- TEST UNIQUE AND NOT NULL
INSERT INTO R VALUES (1, 2, 3, 4, 5, 'W');
INSERT INTO R VALUES (6, 7, 8, 9, 10, 'W');
SELECT * FROM R;

-- NOT NULL;
INSERT INTO R VALUES (1, 2, 3, 4, NULL, 'W');
INSERT INTO R VALUES (1, 2, 3, NULL, 4, 'W');
INSERT INTO R VALUES (1, 2, NULL, 3, 4, 'W');
INSERT INTO R VALUES (1, NULL, 2, 3, 4, 'W');
INSERT INTO R VALUES (NULL, 1, 2, 3, 4, 'W');
SELECT * FROM R;

-- UNIQUE;
INSERT INTO R VALUES (6, 7, 8, 9, 11, 'X'); -- FAIL;
SELECT * FROM R;
INSERT INTO R VALUES (6, 7, 9, 9, 12, 'X'); -- SUCC;
SELECT * FROM R;
INSERT INTO R VALUES (6, 9, 8, 9, 12, 'X'); -- SUCC;
SELECT * FROM R;
INSERT INTO R VALUES (9, 7, 8, 9, 12, 'X'); -- SUCC;
SELECT * FROM R;

-- DROP PRIMARY KEY BY WRONG NAME;
ALTER TABLE R DROP PRIMARY KEY WRONG_NAME;
DESC R;

-- DROP PRIMARY KEY WITHOUT ANY NAME;
ALTER TABLE R DROP PRIMARY KEY;
DESC R;

-- ADD PRIMARY KEY THROUGH ALTER TABLE;
ALTER TABLE R ADD CONSTRAINT PK_NAME PRIMARY KEY (Y, X);
DESC R;
ALTER TABLE R DROP PRIMARY KEY PK_NAME;
DESC R;

-- CREATE TABLE FAILURE;
CREATE TABLE P (
    A INT,
    B INT,
    C INT,
    D INT,
    E VARCHAR(100),

    FOREIGN KEY test_fk (A, B, C) REFERENCES R (Z, Y, X)
);
SHOW TABLES;
DESC P;

-- CREATE TABLE SUCC;
ALTER TABLE R ADD CONSTRAINT PK_NAME PRIMARY KEY (Z, Y, X);
CREATE TABLE P (
   A INT,
   B INT,
   C INT,
   D INT,
   E VARCHAR(100),

   FOREIGN KEY test_fk (A, B, C) REFERENCES R (Z, Y, X)
);
SHOW TABLES;
DESC P;