USE DATASET;

-- SELECT * FROM CUSTOMER;
SELECT * FROM LINEITEM LIMIT 1 OFFSET 34;
-- SELECT * FROM NATION;
-- SELECT * FROM ORDERS;
-- SELECT * FROM PART;
-- SELECT * FROM PARTSUPP;
-- SELECT * FROM REGION;
-- SELECT * FROM SUPPLIER;