name: CMake

on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: System Info
      run: |
        python --version
        gcc --version
        g++ --version
        cmake --version        
        java -version

    - name: Configure GCC/G++ 11
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install -y g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50

    - name: Configure Dependencies
      run: |
        sudo apt-get install python3-dev
        sudo apt-get install libboost-all-dev
        pip install "conan<2.0"
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
        mkdir $BUILD_DIR
        pushd $BUILD_DIR
        conan install ${{github.workspace}} 
        popd

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -C ${{env.BUILD_TYPE}}
      
