name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc-11
      run: |
        sudo apt-get install -y gcc-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50

    - name: Install g++-11
      run: |
        sudo apt-get install -y g++-11
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50

    - name: Genarate Grammar CPP Files
      - run: ${{github.workspace}}/utils/generate_grammar.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/buildl
      run: ctest -C ${{env.BUILD_TYPE}}
      
