CREATE DATABASE test_db0;
CREATE DATABASE test_db1;
SHOW DATABASES;
USE test_db0;

CREATE TABLE t0(
     a INT,
     b INT,
     c VARCHAR(20) NOT NULL,
     d FLOAT DEFAULT -1.1,

     PRIMARY KEY pk_name (a, b)
);


SELECT * FROM t0;

INSERT INTO t0 VALUES (1, 2, 'TEST_CHARS', 2.71828);

SELECT * FROM t0;

INSERT INTO t0 VALUES (3, 4, 'whatever', 3.1415926);

SELECT * FROM t0;

INSERT INTO t0 VALUES (3, 6, 'whatever2', 3.1415926);

SELECT * FROM t0;

SELECT * FROM t0 WHERE t0.c LIKE '%w_a_e%';